owner: HakaiInstitute # Your GitHub organization or username, where this repository lives
repo: upptime-trial # The name of this repository

sites:
  - name: Hakai.org Homepage
    url: https://hakai.org/
    maxResponseTime: 5000 # 5 seconds

  - name: Hakai.org Wordpress Login Page
    url: https://hakai.org/hakaiinstitutelogin/"
    method: GET
    # method: POST
    # headers:
    #   - "Content-Type: application/x-www-form-urlencoded"
    # body: '{ "log": $WP_UPTIME_LOGIN_TEST_USERNAME, "pwd": $WP_UPTIME_LOGIN_TEST_PASSWORD, "wp-submit": "Log In", "redirect_to": "https://wordpress-675610-2219525.cloudwaysapps.com/wp-admin" }'
    maxResponseTime: 5000 # 5 seconds

  - name: Hakai Magazine Homepage
    url: https://www.hakaimagazine.com/
    maxResponseTime: 5000 # 5 seconds

  - name: Hakai Magazine Wordpress Login Page
    url: https://www.hakaimagazine.com/hakaimagazinelogin/
    maxResponseTime: 5000 # 5 seconds

  - name: CIOOS Pacific Homepage
    url: https://cioospacific.ca/
    maxResponseTime: 5000 # 5 seconds

  - name: CIOOS Pacific Wordpress Login Page
    url: https://cioospacific.ca/wp-admin/
    maxResponseTime: 5000 # 5 seconds

  - name: Marine Heatwaves Production
    url: https://hakaiinstitute.github.io/ssta_images/dist/
    maxResponseTime: 5000 # 5 seconds

  - name: Marine Heatwaves Production Detecting Observable Runtime Errors
    url: https://hakaiinstitute.github.io/ssta_images/dist/
    __dangerous__body_down: "RuntimeError"

  - name: ICO Production
    url: https://ico.hakai.org/
    maxResponseTime: 5000 # 5 seconds

  - name: ICO Production Detecting Observable Runtime Errors
    url: https://ico.hakai.org/
    __dangerous__body_down: "RuntimeError"

  - name: Hakai CKAN Catalogue
    url: https://catalogue.hakai.org/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - fostermh

  - name: Hakai CKAN Catalogue Sitemap
    url: https://catalogue.hakai.org/sitemap/sitemap-1.xml
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - fostermh

  - name: MaPP CKAN Catalogue
    url: https://metadata.mappocean.org/
    maxResponseTime: 5000 # 5 seconds
    headers:
      - "Authorization: Basic $MAPP_UPTIME_CKAN_BASIC_AUTH"
    assignees: # Users to assign downtime issues (optional)
      - fostermh

  - name: IYS CKAN Catalogue
    url: https://iys.hakai.org/dataset
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - fostermh

  - name: IYS CKAN Catalogue Sitemap
    url: https://iys.hakai.org/sitemap/sitemap-1.xml
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - fostermh

  - name: Algae Explorer Public Website
    url: https://algaeexplorer.ca/
    maxResponseTime: 5000 # 5 seconds
    assignees: # Users to assign downtime issues (optional)
      - steviewanders
    


assignees: # Users to assign downtime issues (optional)
  - steviewanders

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #   cname: demo.upptime.js.org
  baseUrl: /upptime-trial
  logoUrl: https://github.com/HakaiInstitute/upptime-trial/blob/master/hakai-logo.svg
  theme: light
  name: Hakai Institute Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/HakaiInstitute/upptime-trial). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
